### ISSUE TITLE
Incompatible dependency on scalatest

### ISSUE THREAD

**Issue by kubukoz** [typelevel/cats-testkit-scalatest#18]
Hi!

As mentioned [on gitter](https://gitter.im/typelevel/cats-dev?at=5d90cea20e829f60474a9c81), cats-testkit-scalatest depends on scalatest 3.1.0-RC2 and discipline-scalatest 1.0.0-M1, which depends on scalatest 3.1.0-SNAP13. This causes a binary incompatibility, so:

- [x] discipline-scalatest should update its scalatest dependency to RC
- [ ] cats-testkit-scalatest should update its discipline after the above is released

**Comment by kubukoz** [comment]
@larsrh

**Comment by tovbinm** [comment]
I think this what causes `java.lang.NoClassDefFoundError: org/scalatest/Matchers` error in my project as well.

**Comment by kubukoz** [comment]
That's the one. :)

**Comment by larsrh** [comment]
Will update & release this as soon as the discipline-scalatest artifact appears on Maven Central.

**Comment by larsrh** [comment]
`v1.0.0-RC1`
